import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = fileURLToPath(new URL('../', import.meta.url));
const assets = path.join(root, 'src/assets/cursors');
const template = path.join(assets, 'template.css');
const output = path.join(root, 'src/styles/cursors.css');

// One-time, lossless recovery of the sprites already approved in this project.
// Refuse to overwrite the recovered source. Normal runs never need this option.
if (process.argv.includes('--extract-legacy')) {
  if (existsSync(template)) throw new Error('Cursor source already exists');
  mkdirSync(assets, { recursive: true });
  let index = 0;
  const source = readFileSync(output, 'utf8').replace(/url\(data:image\/png;base64,([A-Za-z0-9+/=]+)\)/g, (_, data) => {
    const name = `frame-${index++}.png`;
    writeFileSync(path.join(assets, name), Buffer.from(data, 'base64'));
    return `url(./${name})`;
  });
  if (index !== 8) throw new Error(`Expected 8 legacy frames, found ${index}`);
  writeFileSync(template, source);
}

const css = readFileSync(template, 'utf8').replace(/url\(\.\/(frame-\d+\.png)\)/g, (_, name) =>
  `url(data:image/png;base64,${readFileSync(path.join(assets, name)).toString('base64')})`);
const generated = '/* Generated by npm run cursors. Edit src/assets/cursors, not this file. */\n' + css;
if (process.argv.includes('--check')) {
  if (readFileSync(output, 'utf8') !== generated) throw new Error('Run npm run cursors and commit the result');
} else {
  writeFileSync(output, generated);
}
